services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - ~/.gitconfig:/root/.gitconfig:ro
    environment:
      - JUPYTER_ENABLE_LAB=yes
      # The token is set to empty for local convenience; change this in a production setting
      - JUPYTER_TOKEN=
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
