"""
Manual feature engineering test script.
Tests several hand-crafted candidate features from untried categories.
Run inside Docker container:
  python3 test_features_manual.py
"""
import sys, os, subprocess, json
sys.path.insert(0, "src")

BASELINE_FOLDS = {0: 0.35797, 1: 0.38811, 3: 0.36936, 4: 0.40072}
PROBE_FOLDS = [0, 1, 3, 4]

CANDIDATES = {
    "yoy_anchor_combo": """
features = features.with_columns([
    # Multi-year geometric anchor — the square root of last-year * 2yr-ago count gives a
    # stable baseline that is robust to a single outlier year.
    (pl.col("target_lag_1yr").fill_null(0).cast(pl.Float64) *
     pl.col("target_lag_2yr").fill_null(0).cast(pl.Float64)).sqrt()
    .alias("target_lag_geomean"),
    # How far is the customer's recent 3-month rate (annualised) above/below last year?
    (pl.col("txn_count_last_3m").fill_null(0).cast(pl.Float64) * 4.0 /
     pl.col("target_lag_1yr").fill_null(0).cast(pl.Float64).clip(lower_bound=1.0))
    .alias("recent_vs_lag1yr_ratio"),
])""",

    "monthly_vol_stddev": """
features = features.with_columns([
    # Standard deviation of monthly transaction counts over m1-m6 — measures how
    # consistent vs spiky the customer is. Low stddev = predictable behaviour.
    (
        (
            (pl.col("txn_count_m1").fill_null(0).cast(pl.Float64) - pl.col("txn_count_6m_avg").fill_null(0)).pow(2) +
            (pl.col("txn_count_m2").fill_null(0).cast(pl.Float64) - pl.col("txn_count_6m_avg").fill_null(0)).pow(2) +
            (pl.col("txn_count_m3").fill_null(0).cast(pl.Float64) - pl.col("txn_count_6m_avg").fill_null(0)).pow(2) +
            (pl.col("txn_count_m4").fill_null(0).cast(pl.Float64) - pl.col("txn_count_6m_avg").fill_null(0)).pow(2) +
            (pl.col("txn_count_m5").fill_null(0).cast(pl.Float64) - pl.col("txn_count_6m_avg").fill_null(0)).pow(2) +
            (pl.col("txn_count_m6").fill_null(0).cast(pl.Float64) - pl.col("txn_count_6m_avg").fill_null(0)).pow(2)
        ) / 6.0
    ).sqrt().alias("monthly_vol_std_6m"),
])""",

    "interest_revenue_ratio": """
features = features.with_columns([
    # Interest revenue relative to transaction volume — a proxy for balance quality
    # (high-balance / credit-active customers have different forecast dynamics)
    (pl.col("fin_interest_revenue_mean").fill_null(0).cast(pl.Float64) /
     pl.col("txn_count_last_3m").fill_null(0).cast(pl.Float64).clip(lower_bound=1.0))
    .alias("interest_per_txn_3m"),
])""",

    "balance_per_txn": """
features = features.with_columns([
    # Average balance per transaction in the last 3m — high-balance low-frequency users
    # behave very differently from low-balance high-frequency users
    (pl.col("stmt_balance_mean_3m").fill_null(0).cast(pl.Float64).abs() /
     pl.col("txn_count_last_3m").fill_null(0).cast(pl.Float64).clip(lower_bound=1.0))
    .alias("balance_per_txn_3m"),
])""",

    "yoy_geomean_plus_balance": """
features = features.with_columns([
    (pl.col("target_lag_1yr").fill_null(0).cast(pl.Float64) *
     pl.col("target_lag_2yr").fill_null(0).cast(pl.Float64)).sqrt()
    .alias("target_lag_geomean"),
    (pl.col("stmt_balance_mean_3m").fill_null(0).cast(pl.Float64).abs() /
     pl.col("txn_count_last_3m").fill_null(0).cast(pl.Float64).clip(lower_bound=1.0))
    .alias("balance_per_txn_3m"),
    (
        (
            (pl.col("txn_count_m1").fill_null(0).cast(pl.Float64) - pl.col("txn_count_6m_avg").fill_null(0)).pow(2) +
            (pl.col("txn_count_m2").fill_null(0).cast(pl.Float64) - pl.col("txn_count_6m_avg").fill_null(0)).pow(2) +
            (pl.col("txn_count_m3").fill_null(0).cast(pl.Float64) - pl.col("txn_count_6m_avg").fill_null(0)).pow(2) +
            (pl.col("txn_count_m4").fill_null(0).cast(pl.Float64) - pl.col("txn_count_6m_avg").fill_null(0)).pow(2) +
            (pl.col("txn_count_m5").fill_null(0).cast(pl.Float64) - pl.col("txn_count_6m_avg").fill_null(0)).pow(2) +
            (pl.col("txn_count_m6").fill_null(0).cast(pl.Float64) - pl.col("txn_count_6m_avg").fill_null(0)).pow(2)
        ) / 6.0
    ).sqrt().alias("monthly_vol_std_6m"),
    (pl.col("txn_count_last_3m").fill_null(0).cast(pl.Float64) * 4.0 /
     pl.col("target_lag_1yr").fill_null(0).cast(pl.Float64).clip(lower_bound=1.0))
    .alias("recent_vs_lag1yr_ratio"),
])""",
}

# ---- read/write helpers -----
START_TAG = "    ### AUTOGENERATED FEATURES ###"
END_TAG   = "    ### END AUTOGENERATED FEATURES ###"

def read_features_py():
    with open("src/features.py") as f:
        return f.read()

def write_features_py(content):
    with open("src/features.py", "w") as f:
        f.write(content)

def inject_block(original, block):
    idx_s = original.find(START_TAG)
    idx_e = original.find(END_TAG)
    indented = "\n".join("    " + line for line in block.strip().splitlines())
    return original[:idx_s] + START_TAG + "\n" + indented + "\n" + original[idx_e:]

def run_eval(folds):
    cmd = [sys.executable, "src/fast_eval.py", "--folds", ",".join(str(f) for f in folds)]
    env = os.environ.copy(); env["PYTHONUNBUFFERED"] = "1"
    result = subprocess.run(cmd, capture_output=True, text=True, env=env)
    scores = {}
    avg = None
    for line in result.stdout.splitlines():
        if line.startswith("FOLD_SCORES_JSON="):
            scores = {int(k): float(v) for k, v in json.loads(line.split("=",1)[1]).items()}
        elif line.startswith("FINAL_AVG="):
            avg = float(line.split("=",1)[1])
    return scores, avg, result.stdout[-500:] if avg is None else ""

# ---- run each candidate -----
original = read_features_py()
results = []

print(f"Baseline folds {PROBE_FOLDS}: avg={sum(BASELINE_FOLDS[f] for f in PROBE_FOLDS)/len(PROBE_FOLDS):.5f}")
print()

for name, block in CANDIDATES.items():
    print(f"Testing: {name} ...")
    injected = inject_block(original, block)
    write_features_py(injected)
    scores, avg, err = run_eval(PROBE_FOLDS)
    write_features_py(original)  # always revert

    if avg is None:
        print(f"  CRASH: {err[:200]}")
        results.append((name, None, None))
        continue

    baseline_avg = sum(BASELINE_FOLDS[f] for f in PROBE_FOLDS) / len(PROBE_FOLDS)
    delta = baseline_avg - avg
    per_fold = {f: round(BASELINE_FOLDS[f] - scores.get(f, float('inf')), 5) for f in PROBE_FOLDS}
    print(f"  avg={avg:.5f}  delta={delta:+.5f}  per_fold={per_fold}")
    results.append((name, avg, delta))

print()
print("=== SUMMARY ===")
for name, avg, delta in sorted(results, key=lambda x: x[2] if x[2] is not None else -999, reverse=True):
    if delta is None:
        print(f"  {name}: CRASH")
    else:
        print(f"  {name}: delta={delta:+.5f}  ({'BEAT BASELINE' if delta > 0 else 'worse'})")
