import os
import sys
import re
import time
import subprocess
import textwrap
from google import genai
import sys
sys.path.append('src')
import features

# Configure this with your actual API key or via environment variable
api_key = os.environ.get("GEMINI_API_KEY", "")
client = None
if api_key:
    client = genai.Client(api_key=api_key)

FAST_EVAL_FILE = "src/fast_eval.py"

TARGET_FILES = {
    "src/features.py": ("### AUTOGENERATED FEATURES ###", "### END AUTOGENERATED FEATURES ###"),
    "src/fast_eval.py": ("### AUTOGENERATED HYPERPARAMETERS ###", "### END AUTOGENERATED HYPERPARAMETERS ###"),
    "src/train.py": ("### AUTOGENERATED PIPELINE ###", "### END AUTOGENERATED PIPELINE ###"),
    "src/train_xgb.py": ("### AUTOGENERATED PIPELINE ###", "### END AUTOGENERATED PIPELINE ###"),
    "src/train_cat.py": ("### AUTOGENERATED PIPELINE ###", "### END AUTOGENERATED PIPELINE ###"),
    "src/tune_lgbm.py": ("### AUTOGENERATED TUNING SPACE ###", "### END AUTOGENERATED TUNING SPACE ###")
}

def read_file(filepath):
    with open(filepath, "r", encoding="utf-8") as f:
        return f.read()

def write_file(filepath, content):
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

def read_all_files():
    return {filepath: read_file(filepath) for filepath in TARGET_FILES}

def write_all_files(file_contents):
    for filepath, content in file_contents.items():
        write_file(filepath, content)

def extract_autogen_block(content, start_tag, end_tag):
    pattern = rf"({re.escape(start_tag)}\n)(.*?)(\n\s*{re.escape(end_tag)})"
    match = re.search(pattern, content, flags=re.DOTALL)
    if match:
        return match.group(2)
    return ""

def inject_autogen_block(content, new_block, start_tag, end_tag):
    pattern = rf"({re.escape(start_tag)}\n)(.*?)(\n\s*{re.escape(end_tag)})"
    # Normalize indentation: dedent to remove common whitespace, then indent exactly 4 spaces
    # Exception: if new_block is empty, don't indent
    if new_block.strip():
        new_block = textwrap.dedent(new_block.strip("\n"))
        new_block = textwrap.indent(new_block, '    ')
    else:
        new_block = ""
    
    # Use lambda to avoid issues with backreferences in replacement string
    return re.sub(pattern, lambda m: f"{m.group(1)}{new_block}{m.group(3)}", content, flags=re.DOTALL)

def run_evaluation(baseline_score):
    try:
        cmd = [sys.executable, FAST_EVAL_FILE, "--baseline", str(baseline_score), "--log-reward"]
        result = subprocess.run(cmd, capture_output=True, text=True)
        # Parse output for FINAL_SCORE
        for line in result.stdout.splitlines():
            if line.startswith("FINAL_SCORE="):
                return float(line.split("=")[1]), ""
        print("Failed to parse FINAL_SCORE from output")
        # Combine stdout and stderr for debugging feedback to the agent
        return float("inf"), result.stdout + "\n" + result.stderr
    except Exception as e:
        print(f"Evaluation failed to run: {e}")
        return float("inf"), str(e)

def generate_new_code(current_files_state, baseline_score, previous_attempts="", schema=""):
    if not api_key:
        print("WARNING: GEMINI_API_KEY not set. Generating a dummy feature for testing.")
        return {"src/features.py": 'features = features.with_columns([(pl.col("txn_count_all") * 2).alias("test_autogen_feature")])'}
    
    prompt = f"""
You are an expert data scientist participating in the Zindi Nedbank Transaction Volume Forecasting challenge.
The target metric is Root Mean Squared Logarithmic Error (RMSLE). Lower is better.
The current baseline proxy RMSLE score is: {baseline_score:.5f}.

The `features` dataframe has the following columns available:
{schema}

You have access to inject code into the following files simultaneously:
1. `src/features.py` (Generate new polars features)
2. `src/fast_eval.py` (Tune proxy LightGBM parameters - THIS IS THE ONLY FILE EVALUATED FOR THE LOOP SCORE)
3. `src/train.py` (Tune final pipeline / LightGBM parameters)
4. `src/train_xgb.py` (Tune XGBoost parameters)
5. `src/train_cat.py` (Tune CatBoost parameters)
6. `src/tune_lgbm.py` (Tune Optuna search space)

Note: Only changes to `src/fast_eval.py` and `src/features.py` will impact the immediate proxy RMSLE score. However, you should update the other files to keep their hyperparameters or pipelines aligned with the feature set so the final models benefit.

To inject code, you MUST format your response using markdown code blocks with the filename specified right after the language. For example:

```python:src/features.py
features = features.with_columns(
    pl.col("txn_count_all").shift(1).alias("lag_1")
)
```

```python:src/train_xgb.py
params["learning_rate"] = 0.05
params["max_depth"] = 8
```

Previous attempts and feedback:
{previous_attempts}

Please output the code blocks to inject. You do not need to provide blocks for all files, only the ones you wish to change.
"""
    try:
        if client:
            response = client.models.generate_content(
                model="gemma-4-31b-it",
                contents=prompt
            )
        else:
            print("No client configured.")
            return None
            
        text = response.text
        
        # Parse output for ```python:filename ... ```
        pattern = r"```python:(.+?)\n(.*?)```"
        matches = re.findall(pattern, text, flags=re.DOTALL)
        
        results = {}
        if matches:
            for filename, code in matches:
                filename = filename.strip()
                if filename in TARGET_FILES:
                    results[filename] = code.strip("\n")
        else:
            # Fallback if the LLM ignores the format and just outputs a python block
            code = re.sub(r"^```python\s*", "", text)
            code = re.sub(r"^```\s*", "", code)
            code = re.sub(r"\s*```$", "", code)
            if code.strip():
                results["src/features.py"] = code.strip("\n")
                
        return results
    except Exception as e:
        error_str = str(e)
        print(f"LLM API Error: {error_str}")
        
        match = re.search(r"retry in ([\d\.]+)s", error_str)
        if match:
            wait_time = float(match.group(1)) + 5.0
            print(f"Rate limit hit. Waiting for {wait_time:.1f} seconds...")
            time.sleep(wait_time)
            
        return None

def main():
    print("Starting Automated Multi-File Engineering Loop...")
    
    print("Extracting feature schema...")
    try:
        df_schema = features.create_features(data_dir='data/inputs')
        schema_str = ", ".join(df_schema.columns)
        print(f"Extracted {len(df_schema.columns)} columns for schema.")
    except Exception as e:
        schema_str = f"Error extracting schema: {e}"
        print(schema_str)

    print("Evaluating current baseline...")
    baseline_score, _ = run_evaluation(baseline_score=1.0)
    if baseline_score == float("inf"):
        print("Failed to get initial baseline. Exiting.")
        return
        
    print(f"Initial Baseline RMSLE: {baseline_score:.5f}")
    
    previous_attempts = ""
    iteration = 1
    
    while True:
        print(f"\n--- Iteration {iteration} ---")
        current_files_state = read_all_files()
        
        print("Requesting new code block from LLM...")
        new_blocks = generate_new_code(current_files_state, baseline_score, previous_attempts, schema=schema_str)
        
        if not new_blocks:
            print("Failed to generate code, retrying in 10s...")
            time.sleep(10)
            continue
            
        print(f"Generated Code for files: {list(new_blocks.keys())}")
        
        # Inject into all targeted files
        updated_files_state = current_files_state.copy()
        combined_new_code = ""
        for filepath, new_code in new_blocks.items():
            combined_new_code += f"\n# {filepath}\n{new_code}\n"
            start_tag, end_tag = TARGET_FILES[filepath]
            updated_content = inject_autogen_block(current_files_state[filepath], new_code, start_tag, end_tag)
            updated_files_state[filepath] = updated_content
            
        # Write to disk
        write_all_files(updated_files_state)
        
        # Evaluate
        new_score, error_log = run_evaluation(baseline_score)
        
        if new_score < baseline_score:
            improvement = baseline_score - new_score
            print(f"SUCCESS! Score improved by {improvement:.5f}. New Baseline: {new_score:.5f}")
            baseline_score = new_score
            previous_attempts = f"Attempt {iteration}: Added code. Score improved from {baseline_score + improvement:.5f} to {baseline_score:.5f}.\nCode:\n{combined_new_code}\nKeep building on this!"
        else:
            degradation = new_score - baseline_score
            print(f"FAILED. Score degraded by {degradation:.5f}. Reverting ALL files.")
            # Atomic rollback
            write_all_files(current_files_state)
            
            error_feedback = ""
            if error_log:
                error_feedback = f"\nThe code caused an ERROR during evaluation:\n{error_log[-500:]}\n"
            
            previous_attempts += f"\nAttempt {iteration}: Added code:\n{combined_new_code}\nResult: Score degraded to {new_score:.5f}. {error_feedback}Avoid this pattern."
            
            if len(previous_attempts) > 2000:
                previous_attempts = previous_attempts[-2000:]
                
        iteration += 1
        time.sleep(2)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nInterrupted by user. Exiting gracefully.")
