import os
import sys
import re
import time
import subprocess
import textwrap
from google import genai
import sys
sys.path.append('src')
import features

# Configure this with your actual API key or via environment variable
api_key = os.environ.get("GEMINI_API_KEY", "")
client = None
if api_key:
    client = genai.Client(api_key=api_key)

FAST_EVAL_FILE = "src/fast_eval.py"

TARGET_FILES = {
    "src/features.py": ("### AUTOGENERATED FEATURES ###", "### END AUTOGENERATED FEATURES ###"),
    "src/fast_eval.py": ("### AUTOGENERATED HYPERPARAMETERS ###", "### END AUTOGENERATED HYPERPARAMETERS ###"),
    "src/train.py": ("### AUTOGENERATED PIPELINE ###", "### END AUTOGENERATED PIPELINE ###"),
    "src/train_xgb.py": ("### AUTOGENERATED PIPELINE ###", "### END AUTOGENERATED PIPELINE ###"),
    "src/train_cat.py": ("### AUTOGENERATED PIPELINE ###", "### END AUTOGENERATED PIPELINE ###"),
    "src/tune_lgbm.py": ("### AUTOGENERATED TUNING SPACE ###", "### END AUTOGENERATED TUNING SPACE ###")
}

def read_file(filepath):
    with open(filepath, "r", encoding="utf-8") as f:
        return f.read()

def write_file(filepath, content):
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

def read_all_files():
    return {filepath: read_file(filepath) for filepath in TARGET_FILES}

def write_all_files(file_contents):
    for filepath, content in file_contents.items():
        write_file(filepath, content)

def extract_autogen_block(content, start_tag, end_tag):
    pattern = rf"({re.escape(start_tag)}\n)(.*?)(\n\s*{re.escape(end_tag)})"
    match = re.search(pattern, content, flags=re.DOTALL)
    if match:
        return match.group(2)
    return ""

def inject_autogen_block(content, new_block, start_tag, end_tag):
    pattern = rf"({re.escape(start_tag)}\n)(.*?)(\n\s*{re.escape(end_tag)})"
    # Normalize indentation: dedent to remove common whitespace, then indent exactly 4 spaces
    # Exception: if new_block is empty, don't indent
    if new_block.strip():
        new_block = textwrap.dedent(new_block.strip("\n"))
        new_block = textwrap.indent(new_block, '    ')
    else:
        new_block = ""
    
    # Use lambda to avoid issues with backreferences in replacement string
    return re.sub(pattern, lambda m: f"{m.group(1)}{new_block}{m.group(3)}", content, flags=re.DOTALL)

def run_evaluation(baseline_score, fold_idx=0):
    try:
        cmd = [sys.executable, FAST_EVAL_FILE, "--baseline", str(baseline_score), "--log-reward", "--fold", str(fold_idx)]
        result = subprocess.run(cmd, capture_output=True, text=True)
        
        score = float("inf")
        top_features = ""
        
        # Parse output for FINAL_SCORE and TOP_FEATURES
        for line in result.stdout.splitlines():
            if line.startswith("FINAL_SCORE="):
                score = float(line.split("=")[1])
            elif line.startswith("TOP_FEATURES="):
                top_features = line.split("=")[1]
                
        if score != float("inf"):
            return score, top_features, ""
            
        print("Failed to parse FINAL_SCORE from output")
        # Combine stdout and stderr for debugging feedback to the agent
        return float("inf"), "", result.stdout + "\n" + result.stderr
    except Exception as e:
        print(f"Evaluation failed to run: {e}")
        return float("inf"), "", str(e)

def execute_analyze_block(code_block):
    # Create a temporary script to execute the EDA code
    script_content = f"""
import os
import sys
import pandas as pd
import numpy as np
import polars as pl
sys.path.append('src')
import features

print("--- Loading Data for Analysis ---")
data_dir = 'data'
try:
    features_df = features.create_features(data_dir=os.path.join(data_dir, 'inputs')).to_pandas()
    train = pd.read_csv(os.path.join(data_dir, 'inputs', 'Train.csv'))
    df = train.merge(features_df, on='UniqueID', how='left')
    
    # Run the agent's code
    print("--- Executing Agent Code ---")
{textwrap.indent(code_block, '    ')}
except Exception as e:
    import traceback
    traceback.print_exc()
"""
    temp_script = "temp_eda_run.py"
    try:
        with open(temp_script, "w", encoding="utf-8") as f:
            f.write(script_content)
        cmd = [sys.executable, temp_script]
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
        output = result.stdout + "\n" + result.stderr
        return output
    except subprocess.TimeoutExpired:
        return "ERROR: Execution timed out after 60 seconds."
    except Exception as e:
        return f"ERROR: Failed to run analyze block: {e}"
    finally:
        if os.path.exists(temp_script):
            os.remove(temp_script)

def generate_new_code(current_files_state, baseline_score, previous_attempts="", schema="", top_features="", is_correction=False):
    if not api_key:
        print("WARNING: GEMINI_API_KEY not set. Generating a dummy feature for testing.")
        return {"src/features.py": 'features = features.with_columns([(pl.col("txn_count_all") * 2).alias("test_autogen_feature")])'}
    
    correction_prompt = ""
    if is_correction:
        correction_prompt = "\nURGENT: Your previous code crashed with an error. Please review the feedback and FIX the code so it runs successfully.\n"

    top_features_prompt = ""
    if top_features:
        top_features_prompt = f"\nTop 10 Most Important Features in the Proxy Model:\n{top_features}\nBuild upon these features or create variations of them!\n"

    prompt = f"""
You are an expert data scientist participating in the Zindi Nedbank Transaction Volume Forecasting challenge.
The target metric is Root Mean Squared Logarithmic Error (RMSLE). Lower is better.
The current baseline proxy RMSLE score is: {baseline_score:.5f}.{correction_prompt}{top_features_prompt}

The `features` dataframe has the following columns available:
{schema}

You have access to inject code into the following files simultaneously:
1. `src/features.py` (Generate new polars features)
2. `src/fast_eval.py` (Tune proxy LightGBM parameters - THIS IS THE ONLY FILE EVALUATED FOR THE LOOP SCORE)
3. `src/train.py` (Tune final pipeline / LightGBM parameters)
4. `src/train_xgb.py` (Tune XGBoost parameters)
5. `src/train_cat.py` (Tune CatBoost parameters)
6. `src/tune_lgbm.py` (Tune Optuna search space)

Note: Only changes to `src/fast_eval.py` and `src/features.py` will impact the immediate proxy RMSLE score. However, you should update the other files to keep their hyperparameters or pipelines aligned with the feature set so the final models benefit.

**Few-Shot Examples for Complex Features:**
Do not just add columns together. Consider complex temporal features, rolling statistics, and conditional logic. Example:
```python:src/features.py
features = features.with_columns([
    (pl.col("txn_amount_sum_all").rolling_mean(window_size=7).over("UniqueID")).alias("rolling_amount_7d"),
    ((pl.col("txn_count_all") / (pl.col("txn_count_all").shift(7).over("UniqueID") + 1))).alias("wow_growth_ratio"),
    pl.when(pl.col("Gender") == "M").then(pl.col("txn_amount_sum_all")).otherwise(0).alias("male_spend")
])
```

**DATA AWARENESS (REPL):**
If you are unsure what features to create, you can run Python code to analyze the data! 
If you output a code block named `python:analyze`, it will NOT be injected into the repository. Instead, it will be executed in a sandboxed pandas environment (with the merged `df` already loaded), and the output will be returned to you in the next prompt.
Example EDA script:
```python:analyze
print("Correlations with target:")
print(df.corr(numeric_only=True)['next_3m_txn_count'].sort_values().head(10))
print(df['Gender'].value_counts())
```
If you use an analyze block, do NOT output any other code blocks. Wait for the observation results!

To inject code, you MUST format your response using markdown code blocks with the filename specified right after the language. For example:

```python:src/features.py
features = features.with_columns(
    pl.col("txn_count_all").shift(1).over("UniqueID").alias("lag_1")
)
```

```python:src/fast_eval.py
params["learning_rate"] = 0.05
params["max_depth"] = 8
```

Previous attempts and feedback:
{previous_attempts}

Please output the code blocks to inject or an analyze block. You do not need to provide blocks for all files, only the ones you wish to change.
"""
    try:
        if client:
            response = client.models.generate_content(
                model="gemma-4-31b-it",
                contents=prompt
            )
        else:
            print("No client configured.")
            return None
            
        text = response.text
        
        # Parse output for ```python:filename ... ```
        pattern = r"```python:(.+?)\n(.*?)```"
        matches = re.findall(pattern, text, flags=re.DOTALL)
        
        results = {}
        if matches:
            for filename, code in matches:
                filename = filename.strip()
                if filename == "analyze":
                    results["analyze"] = code.strip("\n")
                elif filename in TARGET_FILES:
                    results[filename] = code.strip("\n")
        else:
            # Fallback if the LLM ignores the format and just outputs a python block
            code = re.sub(r"^```python\s*", "", text)
            code = re.sub(r"^```\s*", "", code)
            code = re.sub(r"\s*```$", "", code)
            if code.strip():
                results["src/features.py"] = code.strip("\n")
                
        return results
    except Exception as e:
        error_str = str(e)
        print(f"LLM API Error: {error_str}")
        
        match = re.search(r"retry in ([\d\.]+)s", error_str)
        if match:
            wait_time = float(match.group(1)) + 5.0
            print(f"Rate limit hit. Waiting for {wait_time:.1f} seconds...")
            time.sleep(wait_time)
            
        return None

import random

def main():
    print("Starting Automated Multi-File Engineering Loop...")
    
    print("Extracting feature schema...")
    try:
        df_schema = features.create_features(data_dir='data/inputs')
        schema_str = ", ".join(df_schema.columns)
        print(f"Extracted {len(df_schema.columns)} columns for schema.")
    except Exception as e:
        schema_str = f"Error extracting schema: {e}"
        print(schema_str)

    print("Evaluating current baseline across all folds...")
    baseline_scores = []
    current_top_features = ""
    for f in range(5):
        score, top_feat, _ = run_evaluation(baseline_score=1.0, fold_idx=f)
        if score == float("inf"):
            print("Failed to get initial baseline. Exiting.")
            return
        baseline_scores.append(score)
        current_top_features = top_feat
        
    average_baseline = sum(baseline_scores) / 5
    print(f"Initial Baselines: {[round(x, 5) for x in baseline_scores]}")
    print(f"Initial Average Baseline: {average_baseline:.5f}")
    if current_top_features:
        print(f"Top initial features: {current_top_features}")
    
    memory = []
    iteration = 1
    
    while True:
        print(f"\n--- Iteration {iteration} ---")
        current_files_state = read_all_files()
        
        # Build memory string
        previous_attempts_str = "\n".join(memory[-10:]) # Keep last 10 attempts
        
        print("Requesting new code block from LLM...")
        new_blocks = generate_new_code(current_files_state, average_baseline, previous_attempts_str, schema_str, current_top_features, is_correction=False)
        
        if not new_blocks:
            print("Failed to generate code, retrying in 10s...")
            time.sleep(10)
            continue
            
        if "analyze" in new_blocks:
            print("Executing LLM Data Analysis Block...")
            output = execute_analyze_block(new_blocks["analyze"])
            memory.append(f"[OBSERVATION] Analyzed data. Output:\n{output[-1500:]}")
            continue
            
        print(f"Generated Code for files: {list(new_blocks.keys())}")
        
        test_fold = random.randint(0, 4)
        print(f"Testing features on random Fold {test_fold}...")
        
        # Helper to inject and evaluate
        def try_blocks(blocks, fold_idx):
            updated_files_state = current_files_state.copy()
            combined_new_code = ""
            for filepath, new_code in blocks.items():
                combined_new_code += f"\n# {filepath}\n{new_code}\n"
                start_tag, end_tag = TARGET_FILES[filepath]
                updated_content = inject_autogen_block(current_files_state[filepath], new_code, start_tag, end_tag)
                updated_files_state[filepath] = updated_content
            write_all_files(updated_files_state)
            return run_evaluation(baseline_scores[fold_idx], fold_idx), combined_new_code
            
        (new_score, top_features, error_log), combined_new_code = try_blocks(new_blocks, test_fold)
        
        # Self-correction sub-loop
        if new_score == float("inf") and error_log:
            print("Code crashed! Entering self-correction sub-loop...")
            correction_feedback = previous_attempts_str + f"\nAttempt {iteration}: Added code:\n{combined_new_code}\nResult: CRASHED with error:\n{error_log[-1000:]}\n"
            corrected_blocks = generate_new_code(current_files_state, average_baseline, correction_feedback, schema_str, current_top_features, is_correction=True)
            if corrected_blocks and "analyze" not in corrected_blocks:
                print(f"Trying corrected code for: {list(corrected_blocks.keys())}")
                # Rollback first
                write_all_files(current_files_state)
                (new_score, top_features, error_log), combined_new_code = try_blocks(corrected_blocks, test_fold)
        
        condensed_code = combined_new_code[:300] + "..." if len(combined_new_code) > 300 else combined_new_code

        if new_score < baseline_scores[test_fold]:
            print(f"Fold {test_fold} improved! Verifying robustness across all remaining folds...")
            new_scores = []
            for f in range(5):
                if f == test_fold:
                    new_scores.append(new_score)
                else:
                    s, _, _ = run_evaluation(baseline_scores[f], f)
                    new_scores.append(s)
            
            new_average = sum(new_scores) / 5
            if new_average < average_baseline:
                improvement = average_baseline - new_average
                print(f"SUCCESS! Global Average improved by {improvement:.5f}. New Avg Baseline: {new_average:.5f}")
                baseline_scores = new_scores
                average_baseline = new_average
                current_top_features = top_features
                memory.append(f"[SUCCESS] Attempt {iteration}: Global Avg improved from {average_baseline + improvement:.5f} to {average_baseline:.5f}. Code:\n{condensed_code}")
            else:
                print(f"OVERFIT DETECTED! Fold {test_fold} improved but Global Average degraded. Rejecting.")
                write_all_files(current_files_state)
                memory.append(f"[OVERFIT] Attempt {iteration}: Improved Fold {test_fold} but degraded overall. Snippet:\n{condensed_code}")
        else:
            degradation = new_score - baseline_scores[test_fold]
            print(f"FAILED. Fold {test_fold} degraded by {degradation:.5f}. Reverting ALL files.")
            # Atomic rollback
            write_all_files(current_files_state)
            
            error_feedback = ""
            if error_log:
                error_feedback = f" ERROR:\n{error_log[-300:]}\n"
            
            memory.append(f"[FAILED] Attempt {iteration}: Fold {test_fold} degraded to {new_score:.5f}.{error_feedback}Code snippet:\n{condensed_code}")
                
        iteration += 1
        time.sleep(2)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nInterrupted by user. Exiting gracefully.")
