import argparse
import json
import os
import re
import subprocess
import sys
import textwrap
import time
from dataclasses import dataclass

from google import genai

sys.path.append("src")
import features
from rewards import append_reward_event


for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(line_buffering=True)

FAST_EVAL_FILE = "src/fast_eval.py"
ALL_FOLDS = [0, 1, 2, 3, 4]
FEATURE_SEARCH_FILES = {
    "src/features.py": ("### AUTOGENERATED FEATURES ###", "### END AUTOGENERATED FEATURES ###"),
}
KNOWN_INJECT_FILES = {
    **FEATURE_SEARCH_FILES,
    "src/fast_eval.py": ("### AUTOGENERATED HYPERPARAMETERS ###", "### END AUTOGENERATED HYPERPARAMETERS ###"),
    "src/train.py": ("### AUTOGENERATED PIPELINE ###", "### END AUTOGENERATED PIPELINE ###"),
    "src/train_xgb.py": ("### AUTOGENERATED PIPELINE ###", "### END AUTOGENERATED PIPELINE ###"),
    "src/train_cat.py": ("### AUTOGENERATED PIPELINE ###", "### END AUTOGENERATED PIPELINE ###"),
    "src/tune_lgbm.py": ("### AUTOGENERATED TUNING SPACE ###", "### END AUTOGENERATED TUNING SPACE ###"),
}

api_key = os.environ.get("GEMINI_API_KEY", "")
client = genai.Client(api_key=api_key) if api_key else None


@dataclass
class EvalResult:
    scores: dict
    average: float
    top_features: str = ""
    error_log: str = ""


@dataclass
class AcceptanceResult:
    accepted: bool
    improvement: float
    improved_folds: int
    max_degradation: float
    reason: str


def read_file(filepath):
    with open(filepath, "r", encoding="utf-8") as handle:
        return handle.read()


def write_file(filepath, content):
    with open(filepath, "w", encoding="utf-8") as handle:
        handle.write(content)


def read_files(target_files):
    return {filepath: read_file(filepath) for filepath in target_files}


def write_files(file_contents):
    for filepath, content in file_contents.items():
        write_file(filepath, content)


def inject_autogen_block(content, new_block, start_tag, end_tag):
    pattern = rf"([ \t]*){re.escape(start_tag)}\n(.*?)(\n[ \t]*{re.escape(end_tag)})"

    def repl(match):
        indentation = match.group(1)
        start_line = indentation + start_tag + "\n"
        if new_block.strip():
            block = textwrap.dedent(new_block.strip("\n"))
            block = textwrap.indent(block, indentation)
        else:
            block = ""
        return f"{start_line}{block}{match.group(3)}"

    updated, count = re.subn(pattern, repl, content, flags=re.DOTALL)
    if count != 1:
        raise ValueError(f"Expected one autogen block for {start_tag!r}; found {count}.")
    return updated


def parse_code_blocks(text):
    pattern = r"```python:(.+?)\n(.*?)```"
    matches = re.findall(pattern, text, flags=re.DOTALL)
    results = {}
    if matches:
        for filename, code in matches:
            filename = filename.strip()
            if filename == "analyze":
                results["analyze"] = code.strip("\n")
            elif filename in KNOWN_INJECT_FILES:
                results[filename] = code.strip("\n")
        return results

    code = re.sub(r"^```python\s*", "", text)
    code = re.sub(r"^```\s*", "", code)
    code = re.sub(r"\s*```$", "", code)
    if code.strip():
        results["src/features.py"] = code.strip("\n")
    return results


def parse_eval_output(stdout):
    scores = {}
    average = float("inf")
    top_features = ""
    for line in stdout.splitlines():
        if line.startswith("FOLD_SCORES_JSON="):
            raw = line.split("=", 1)[1]
            scores = {int(k): float(v) for k, v in json.loads(raw).items()}
        elif line.startswith("FINAL_AVG="):
            average = float(line.split("=", 1)[1])
        elif line.startswith("FINAL_SCORE=") and not scores:
            average = float(line.split("=", 1)[1])
        elif line.startswith("TOP_FEATURES="):
            top_features = line.split("=", 1)[1]
    return EvalResult(scores=scores, average=average, top_features=top_features)


def run_evaluation_folds(fold_indices):
    cmd = [
        sys.executable,
        FAST_EVAL_FILE,
        "--folds",
        ",".join(str(fold) for fold in fold_indices),
    ]
    env = os.environ.copy()
    env["PYTHONUNBUFFERED"] = "1"
    process = subprocess.Popen(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
        env=env,
    )
    output_lines = []
    for line in process.stdout:
        output_lines.append(line)
        print(line, end="", flush=True)
    returncode = process.wait()
    output = "".join(output_lines)
    parsed = parse_eval_output(output)
    if returncode != 0 or parsed.average == float("inf") or not parsed.scores:
        return EvalResult(
            scores={},
            average=float("inf"),
            error_log=output,
        )
    return parsed


def evaluate_acceptance(
    baseline_scores,
    candidate_scores,
    min_delta=0.00020,
    max_fold_degradation=0.00025,
    min_improved_folds=3,
):
    common_folds = sorted(set(baseline_scores).intersection(candidate_scores))
    if not common_folds:
        return AcceptanceResult(False, 0.0, 0, float("inf"), "no comparable folds")

    baseline_avg = sum(baseline_scores[fold] for fold in common_folds) / len(common_folds)
    candidate_avg = sum(candidate_scores[fold] for fold in common_folds) / len(common_folds)
    improvement = baseline_avg - candidate_avg
    fold_deltas = {
        fold: baseline_scores[fold] - candidate_scores[fold]
        for fold in common_folds
    }
    improved_folds = sum(delta > 0 for delta in fold_deltas.values())
    max_degradation = max(
        (candidate_scores[fold] - baseline_scores[fold] for fold in common_folds),
        default=0.0,
    )
    if improvement < min_delta:
        return AcceptanceResult(
            False,
            improvement,
            improved_folds,
            max_degradation,
            f"average improvement {improvement:.6f} below {min_delta:.6f}",
        )
    if improved_folds < min_improved_folds:
        return AcceptanceResult(
            False,
            improvement,
            improved_folds,
            max_degradation,
            f"only {improved_folds} folds improved",
        )
    if max_degradation > max_fold_degradation:
        return AcceptanceResult(
            False,
            improvement,
            improved_folds,
            max_degradation,
            f"worst fold degraded by {max_degradation:.6f}",
        )
    return AcceptanceResult(True, improvement, improved_folds, max_degradation, "accepted")


def probe_passed(baseline_scores, candidate_scores, max_fold_degradation):
    result = evaluate_acceptance(
        baseline_scores,
        candidate_scores,
        min_delta=0.0,
        max_fold_degradation=max_fold_degradation,
        min_improved_folds=1,
    )
    return result.accepted, result.reason


def parse_probe_folds(value):
    if value is None or str(value).strip() == "":
        return None
    folds = []
    for part in str(value).split(","):
        part = part.strip()
        if not part:
            continue
        fold = int(part)
        if fold not in ALL_FOLDS:
            raise ValueError(f"Probe fold must be one of {ALL_FOLDS}; got {fold}.")
        folds.append(fold)
    if not folds:
        raise ValueError("--probe-folds must include at least one fold index.")
    deduped = []
    for fold in folds:
        if fold not in deduped:
            deduped.append(fold)
    return deduped


def execute_analyze_block(code_block):
    script_content = f"""
import os
import sys
import pandas as pd
import numpy as np
import polars as pl
sys.path.append('src')
import features

print("--- Loading Data for Analysis ---")
data_dir = 'data'
try:
    features_df = features.create_features(data_dir=os.path.join(data_dir, 'inputs')).to_pandas()
    train = pd.read_csv(os.path.join(data_dir, 'inputs', 'Train.csv'))
    df = train.merge(features_df, on='UniqueID', how='left')

    print("--- Executing Agent Code ---")
{textwrap.indent(code_block, '    ')}
except Exception:
    import traceback
    traceback.print_exc()
"""
    temp_script = "temp_eda_run.py"
    try:
        with open(temp_script, "w", encoding="utf-8") as handle:
            handle.write(script_content)
        result = subprocess.run([sys.executable, temp_script], capture_output=True, text=True, timeout=60)
        return result.stdout + "\n" + result.stderr
    except subprocess.TimeoutExpired:
        return "ERROR: Execution timed out after 60 seconds."
    except Exception as exc:
        return f"ERROR: Failed to run analyze block: {exc}"
    finally:
        if os.path.exists(temp_script):
            os.remove(temp_script)


def _llm_prompt(baseline_score, previous_attempts, schema, top_features, is_correction, lab_notebook):
    correction_prompt = ""
    if is_correction:
        correction_prompt = "\nURGENT: Your previous code crashed. Fix only the feature code so it runs successfully.\n"

    top_features_prompt = ""
    if top_features:
        top_features_prompt = (
            "\nTop 10 most important proxy-model features:\n"
            f"{top_features}\n"
            "Build stable variations around these signals only if they are likely to generalize.\n"
        )

    lab_notebook_prompt = ""
    if lab_notebook:
        lab_notebook_prompt = (
            "\n--- LAB NOTEBOOK (Long-Term Learnings) ---\n"
            f"{lab_notebook}\n"
            "------------------------------------------\n"
        )

    return f"""
You are an expert data scientist participating in the Zindi Nedbank Transaction Volume Forecasting challenge.
The target metric is Root Mean Squared Logarithmic Error (RMSLE). Lower is better.
The current 5-fold proxy RMSLE average is: {baseline_score:.5f}.{correction_prompt}{top_features_prompt}{lab_notebook_prompt}

The `features` dataframe has these columns available:
{schema}

You may inject code into exactly one file:
1. `src/features.py` - generate or drop Polars features inside the existing autogen block.

The evaluator and production training files are fixed. Do not output blocks for `src/fast_eval.py`,
`src/train.py`, `src/train_xgb.py`, `src/train_cat.py`, or `src/tune_lgbm.py`. A proposal that edits those
files will be rejected because the proxy score would not prove final-pipeline improvement.

The autogen block is replaced wholesale on every attempt. Only reference columns listed in the
schema above or columns created earlier in the same generated block. If one new feature depends on
another new feature, create them in separate, sequential `features = features.with_columns(...)`
calls so Polars can resolve the dependency.

UNTRIED DIRECTIONS (strongly prefer these over count combinations):
- `stmt_balance_mean_3m`, `stmt_balance_mean_1m`, `stmt_balance_mean` — balance context. Ratio of
  balance to transaction volume, or balance change signals.
- `txn_amount_sum_last_3m`, `txn_amount_sum_last_1m` — amount-based density: amount per transaction,
  amount per active day, amount consistency over time.
- `target_lag_1yr`, `target_lag_2yr`, `yoy_growth_ratio` — year-on-year anchors. These are the
  ACTUAL prior-year counts for the target period and have never been combined with recent activity.
- `fin_interest_income_mean`, `fin_interest_revenue_mean` — financial engagement signals (untried).
- `reversal_ratio`, `bounced_ratio` — transaction quality/reliability features (untried).
- `mom_accel_1`, `mom_accel_2`, `mom_accel_3`, `mom_jerk` — momentum / acceleration of activity
  trend (these are pre-computed but rarely appear in top features, may benefit from combinations).
- Variance / spread of monthly counts: use `txn_count_m1` through `txn_count_m12` to compute
  the standard deviation or range of monthly activity as a measure of consistency.
- `credit_to_debit_ratio`, `card_to_cash_ratio`, `balance_velocity` — behavioural ratios (untried).

WHAT HAS ALREADY BEEN THOROUGHLY TRIED AND CONSISTENTLY FAILS (do not repeat):
- Any additive combination of `txn_count_last_1m`, `txn_count_last_3m`, `txn_count_m1` — these are
  already strongly correlated and adding them together brings no new signal.
- Log transforms of the top count features (log_txn_count_last_1m etc.) — tried, no benefit.
- Differences between rolling and calendar month counts (`txn_count_last_1m - txn_count_m1`) — tried.
- Subtracting batch/system transactions from total to get "human" volume — tried, no benefit.
- Summing type-based counts (`txn_type_transfers_payments_count_3m`, `txn_type_deposits_count_3m`).
- Multi-horizon sums like `txn_count_last_3m + txn_count_last_6m` or decompositions into 3m slices.

AVOID:
- Avoid one-row-per-customer rolling/window expressions such as `rolling_mean(...).over("UniqueID")`,
  because this autogen block runs after aggregation.
- The container Polars version does not support every horizontal helper. Do not use `pl.std_horizontal`.
  For horizontal sums, minima, and maxima, use explicit column arithmetic, `pl.min_horizontal`, or
  `pl.max_horizontal` over existing numeric columns.

DATA AWARENESS & REFLECTION:
If you are unsure, output only a `python:analyze` block. It will run with a pandas dataframe named `df`
containing Train.csv merged with engineered features.

CRITICAL RULES:
1. Do not include import statements inside injected code blocks.
2. Do not define helper functions unless absolutely necessary.
3. Use ONLY `features = features.with_columns([...])` to add new columns. NEVER use `features.select()`,
   `features.drop()`, or `features.rename()` — these remove existing columns from the pipeline and will
   crash downstream code. Only `with_columns` is safe.
4. Output markdown code blocks exactly like:

```python:src/features.py
features = features.with_columns([
    (pl.col("txn_count_last_1m").fill_null(0).log1p()).alias("example_recent_log_count")
])
```

Previous attempts and feedback:
{previous_attempts}
"""


def generate_new_code(
    baseline_score,
    previous_attempts="",
    schema="",
    top_features="",
    is_correction=False,
    lab_notebook="",
    max_llm_failures=5,
):
    if not api_key:
        print("WARNING: GEMINI_API_KEY not set. Generating a dummy feature for testing.")
        return {"src/features.py": 'features = features.with_columns([(pl.col("txn_count_all") * 2).alias("test_autogen_feature")])'}

    prompt = _llm_prompt(
        baseline_score,
        previous_attempts,
        schema,
        top_features,
        is_correction,
        lab_notebook,
    )
    for attempt in range(1, max_llm_failures + 1):
        try:
            response = client.models.generate_content(
                model=os.environ.get("AGENT_LLM_MODEL", "gemini-2.0-flash"),
                contents=prompt,
            )
            return parse_code_blocks(response.text or "")
        except Exception as exc:
            error_str = str(exc)
            print(f"LLM API Error ({attempt}/{max_llm_failures}): {error_str}")
            retry_match = re.search(r"retry in ([\d\.]+)s", error_str)
            if retry_match:
                wait_time = float(retry_match.group(1)) + 5.0
            else:
                wait_time = min(60.0, 5.0 * (2 ** (attempt - 1)))
            if attempt < max_llm_failures:
                print(f"Waiting {wait_time:.1f}s before retry...")
                time.sleep(wait_time)
    return None


def filter_generated_blocks(blocks, editable_files):
    if not blocks:
        return None, "no code blocks returned"
    if "analyze" in blocks:
        if len(blocks) > 1:
            return {"analyze": blocks["analyze"]}, "analysis block returned with code; running analysis only"
        return blocks, ""
    disallowed = [path for path in blocks if path not in editable_files]
    if disallowed:
        return None, f"rejected disallowed edit blocks: {', '.join(disallowed)}"
    return blocks, ""


def apply_blocks_to_state(current_files_state, blocks, editable_files):
    updated_files_state = current_files_state.copy()
    combined_new_code = ""
    for filepath, new_code in blocks.items():
        combined_new_code += f"\n# {filepath}\n{new_code}\n"
        start_tag, end_tag = editable_files[filepath]
        updated_files_state[filepath] = inject_autogen_block(
            current_files_state[filepath],
            new_code,
            start_tag,
            end_tag,
        )
    write_files(updated_files_state)
    return combined_new_code


def git_has_changes(paths):
    result = subprocess.run(
        ["git", "status", "--porcelain", "--", *paths],
        capture_output=True,
        text=True,
    )
    return bool(result.stdout.strip())


def commit_and_push(paths, commit_msg, auto_push=True):
    subprocess.run(["git", "add", "--", *paths], check=True)
    subprocess.run(["git", "-c", "commit.gpgsign=false", "commit", "-m", commit_msg], check=True)
    if auto_push:
        subprocess.run(["git", "push"], check=True)


def parse_args():
    parser = argparse.ArgumentParser(description="Automated feature-engineering loop with robust fold gates.")
    parser.add_argument("--max-iterations", type=int, default=None, help="Maximum candidate iterations; default unlimited.")
    parser.add_argument("--probe-fold-count", type=int, default=2)
    parser.add_argument("--probe-folds", default=None, help="Comma-separated fold indexes to probe, e.g. 0,1,3,4.")
    parser.add_argument("--accept-min-delta", type=float, default=0.00020)
    parser.add_argument("--max-fold-degradation", type=float, default=0.00025)
    parser.add_argument("--max-llm-failures", type=int, default=5)
    parser.add_argument("--mode", default="feature_search", choices=["feature_search"])
    parser.add_argument("--auto-push", dest="auto_push", action="store_true", default=True)
    parser.add_argument("--no-auto-push", dest="auto_push", action="store_false")
    return parser.parse_args()


def main():
    args = parse_args()
    editable_files = FEATURE_SEARCH_FILES
    editable_paths = list(editable_files)
    explicit_probe_folds = parse_probe_folds(args.probe_folds)

    print("Starting guarded feature-engineering loop...")
    print(f"Mode: {args.mode}; editable files: {editable_paths}")

    if git_has_changes(editable_paths):
        print(
            "Target files already have uncommitted changes. Commit/stash them, or rerun "
            "after restoring the target files so the loop cannot commit pre-existing edits."
        )
        return 2

    print("Extracting feature schema...")
    try:
        df_schema = features.create_features(data_dir="data/inputs")
        schema_str = ", ".join(df_schema.columns)
        print(f"Extracted {len(df_schema.columns)} columns for schema.")
    except Exception as exc:
        schema_str = f"Error extracting schema: {exc}"
        print(schema_str)

    print("Evaluating current baseline across all folds...")
    baseline_eval = run_evaluation_folds(ALL_FOLDS)
    if baseline_eval.average == float("inf"):
        print("Failed to get initial baseline. Exiting.")
        print(baseline_eval.error_log[-1500:])
        return 1

    baseline_scores = baseline_eval.scores
    average_baseline = baseline_eval.average
    current_top_features = baseline_eval.top_features
    print(f"Initial Baselines: {[round(baseline_scores[f], 5) for f in ALL_FOLDS]}")
    print(f"Initial Average Baseline: {average_baseline:.5f}")
    if current_top_features:
        print(f"Top initial features: {current_top_features}")

    if args.max_iterations == 0:
        print("max-iterations=0; baseline smoke check complete.")
        return 0

    memory = []
    iteration = 1
    lab_notebook_path = "data/processed/lab_notebook.md"
    attempt_dir = "data/processed/agent_attempts"
    os.makedirs("data/processed", exist_ok=True)
    os.makedirs(attempt_dir, exist_ok=True)

    def read_lab_notebook():
        if os.path.exists(lab_notebook_path):
            return read_file(lab_notebook_path)
        return "No insights recorded yet."

    def append_lab_notebook(entry):
        current = read_file(lab_notebook_path) if os.path.exists(lab_notebook_path) else ""
        entries = current.split("\n\n---\n\n") if current.strip() else []
        entries.append(entry)
        write_file(lab_notebook_path, "\n\n---\n\n".join(entries[-20:]).strip())

    def write_attempt_artifact(status, code, details):
        slug = re.sub(r"[^a-z0-9]+", "_", status.lower()).strip("_")
        path = os.path.join(attempt_dir, f"iteration_{iteration:03d}_{slug}.py")
        detail_lines = "\n".join(f"# {key}: {value}" for key, value in details.items())
        write_file(path, f"{detail_lines}\n\n{code}")
        return path

    while args.max_iterations is None or iteration <= args.max_iterations:
        print(f"\n--- Iteration {iteration} ---")
        current_files_state = read_files(editable_files)
        previous_attempts_str = "\n".join(memory[-10:])
        notebook_content = read_lab_notebook()

        print("Requesting new feature block from LLM...")
        new_blocks = generate_new_code(
            average_baseline,
            previous_attempts=previous_attempts_str,
            schema=schema_str,
            top_features=current_top_features,
            is_correction=False,
            lab_notebook=notebook_content,
            max_llm_failures=args.max_llm_failures,
        )
        if not new_blocks:
            print("Failed to generate code after bounded retries. Exiting.")
            return 1

        new_blocks, filter_message = filter_generated_blocks(new_blocks, editable_files)
        if filter_message:
            print(filter_message)
            memory.append(f"[REJECTED] {filter_message}")
        if not new_blocks:
            iteration += 1
            continue

        if "analyze" in new_blocks:
            print("Executing LLM data analysis block...")
            output = execute_analyze_block(new_blocks["analyze"])
            memory.append(f"[OBSERVATION] Analyzed data. Output:\n{output[-1500:]}")
            iteration += 1
            continue

        print(f"Generated code for files: {list(new_blocks.keys())}")
        probe_folds = explicit_probe_folds or ALL_FOLDS[: max(1, min(args.probe_fold_count, len(ALL_FOLDS)))]
        print(f"Testing deterministic probe folds: {probe_folds}")

        try:
            combined_new_code = apply_blocks_to_state(current_files_state, new_blocks, editable_files)
        except Exception as exc:
            write_files(current_files_state)
            memory.append(f"[CRASH] Failed to inject generated blocks: {exc}")
            iteration += 1
            continue

        probe_eval = run_evaluation_folds(probe_folds)
        if probe_eval.average == float("inf"):
            print("Code crashed during probe. Reverting feature file.")
            print(probe_eval.error_log[-1000:])
            write_files(current_files_state)
            memory.append(f"[CRASH] Attempt {iteration} probe failed:\n{probe_eval.error_log[-1000:]}")
            iteration += 1
            continue

        ok, reason = probe_passed(
            {fold: baseline_scores[fold] for fold in probe_folds},
            probe_eval.scores,
            args.max_fold_degradation,
        )
        if not ok:
            print(f"Probe rejected: {reason}. Reverting feature file.")
            write_files(current_files_state)
            memory.append(f"[FAILED] Attempt {iteration}: probe rejected ({reason}).")
            append_lab_notebook(f"**PROBE FAIL:**\n{reason}\n```python\n{combined_new_code[:1000]}\n```")
            iteration += 1
            time.sleep(2)
            continue

        print("Probe passed. Verifying all folds...")
        full_eval = run_evaluation_folds(ALL_FOLDS)
        if full_eval.average == float("inf"):
            print("Full verification failed. Reverting feature file.")
            print(full_eval.error_log[-1000:])
            write_files(current_files_state)
            memory.append(f"[CRASH] Attempt {iteration} full verification failed.")
            iteration += 1
            continue

        acceptance = evaluate_acceptance(
            baseline_scores,
            full_eval.scores,
            min_delta=args.accept_min_delta,
            max_fold_degradation=args.max_fold_degradation,
            min_improved_folds=3,
        )
        condensed_code = combined_new_code[:600] + "..." if len(combined_new_code) > 600 else combined_new_code
        if acceptance.accepted:
            artifact_path = write_attempt_artifact(
                "accepted",
                combined_new_code,
                {
                    "status": "accepted",
                    "average_improvement": f"{acceptance.improvement:.9f}",
                    "improved_folds": acceptance.improved_folds,
                    "max_degradation": f"{acceptance.max_degradation:.9f}",
                },
            )
            print(
                "SUCCESS! Global average improved by "
                f"{acceptance.improvement:.6f}; improved_folds={acceptance.improved_folds}; "
                f"max_degradation={acceptance.max_degradation:.6f}."
            )
            baseline_scores = full_eval.scores
            average_baseline = full_eval.average
            current_top_features = full_eval.top_features
            memory.append(
                f"[SUCCESS] Attempt {iteration}: Global Avg improved to {average_baseline:.5f}.\n{condensed_code}"
            )
            append_lab_notebook(
                f"**SUCCESS:**\nRMSLE improved by {acceptance.improvement:.6f}.\n"
                f"Full code artifact: `{artifact_path}`\n```python\n{condensed_code}\n```"
            )
            append_reward_event(
                event_type="agent_feature_gen",
                scenario="fast_eval_5fold",
                improvement=acceptance.improvement,
                old_score=average_baseline + acceptance.improvement,
                new_score=average_baseline,
                source="src/agent_loop.py",
                notes="Accepted only after deterministic probe and full 5-fold verification.",
            )
            try:
                commit_msg = f"Agent: Improved 5-fold RMSLE to {average_baseline:.5f} (delta: -{acceptance.improvement:.5f})"
                commit_and_push(editable_paths, commit_msg, auto_push=args.auto_push)
                print(f"Committed{' and pushed' if args.auto_push else ''}: {commit_msg}")
            except Exception as exc:
                print(f"Accepted improvement, but git commit/push failed: {exc}")
                return 1
        else:
            status = "near_miss" if acceptance.improvement > 0 else "rejected"
            artifact_path = write_attempt_artifact(
                status,
                combined_new_code,
                {
                    "status": status,
                    "reason": acceptance.reason,
                    "average_improvement": f"{acceptance.improvement:.9f}",
                    "improved_folds": acceptance.improved_folds,
                    "max_degradation": f"{acceptance.max_degradation:.9f}",
                },
            )
            print(f"Rejected after full verification: {acceptance.reason}. Reverting feature file.")
            write_files(current_files_state)
            memory.append(f"[REJECTED] Attempt {iteration}: {acceptance.reason}.\n{condensed_code}")
            append_lab_notebook(
                f"**FULL-GATE FAIL:**\n{acceptance.reason}\n"
                f"Full code artifact: `{artifact_path}`\n```python\n{condensed_code}\n```"
            )

        iteration += 1
        time.sleep(2)

    print("Reached max iterations. Exiting.")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        print("\nInterrupted by user. Exiting gracefully.")
