import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.metrics import mean_squared_error
import os
import joblib
from pipeline_utils import CAT_COLS, fit_category_maps, require_nvidia_gpu
from validation import get_validation_splits, validate_fold_partition

def train_xgboost(data_dir='data'):
    require_nvidia_gpu()
    print("Loading data for XGBoost training...")
    train = pd.read_csv(os.path.join(data_dir, 'inputs', 'Train.csv'))
    features = pd.read_parquet(os.path.join(data_dir, 'processed', 'all_features.parquet'))

    print("Merging train labels with engineered features...")
    df = train.merge(features, on='UniqueID', how='left')

    # Persist label maps so train/test categorical codes cannot drift.
    category_maps = fit_category_maps(df, CAT_COLS)

    drop_cols = ['UniqueID', 'BirthDate', 'next_3m_txn_count']
    feature_cols = [c for c in df.columns if c not in drop_cols]

    df[feature_cols] = df[feature_cols].fillna(0)

    X = df[feature_cols].values
    y = np.log1p(df['next_3m_txn_count'].values)

    print(f"Training XGBoost model on {len(X)} rows and {len(feature_cols)} features...")

    folds = get_validation_splits(df, y, n_splits=5, random_state=42)
    validate_fold_partition(folds, len(df))
    oof_preds = np.zeros(len(X))

    params = {
        'objective': 'reg:squarederror',
        'eval_metric': 'rmse',
        'learning_rate': 0.01,
        'max_depth': 8,
        'min_child_weight': 5,
        'subsample': 0.7,
        'colsample_bytree': 0.7,
        'reg_lambda': 1.0,
        'reg_alpha': 0.1,
        'tree_method': 'hist',
        'device': 'cuda',
        'seed': 42
    }

    ### AUTOGENERATED PIPELINE ###
    params["learning_rate"] = 0.03
    params["max_depth"] = 6
    params["subsample"] = 0.8
    params["colsample_bytree"] = 0.7
    params["reg_alpha"] = 0.1
    params["reg_lambda"] = 1.0
    ### END AUTOGENERATED PIPELINE ###

    os.makedirs('models', exist_ok=True)
    os.makedirs(os.path.join(data_dir, 'processed'), exist_ok=True)
    joblib.dump(
        {'feature_cols': feature_cols, 'category_maps': category_maps},
        os.path.join(data_dir, 'processed', 'xgb_preprocessor.joblib'),
    )

    for fold, (train_idx, val_idx) in enumerate(folds):
        X_train, y_train = X[train_idx], y[train_idx]
        X_val, y_val = X[val_idx], y[val_idx]

        dtrain = xgb.DMatrix(X_train, label=y_train)
        dval = xgb.DMatrix(X_val, label=y_val)

        model = xgb.train(
            params,
            dtrain,
            num_boost_round=5000,
            evals=[(dtrain, 'train'), (dval, 'val')],
            early_stopping_rounds=100,
            verbose_eval=500
        )

        oof_preds[val_idx] = model.predict(dval)
        fold_rmse = np.sqrt(mean_squared_error(y_val, oof_preds[val_idx]))
        print(f"Fold {fold+1} Validation RMSLE: {fold_rmse:.4f}")

        model.save_model(f'models/xgb_fold{fold}.json')

    overall_rmse = np.sqrt(mean_squared_error(y, oof_preds))
    print(f"Overall XGBoost OOF RMSLE: {overall_rmse:.4f}")

    oof_df = pd.DataFrame({
        'UniqueID': df['UniqueID'],
        'pred_xgb': oof_preds
    })
    oof_df.to_csv(os.path.join(data_dir, 'processed', 'oof_xgb.csv'), index=False)
    print("OOF predictions saved to data/processed/oof_xgb.csv")

if __name__ == "__main__":
    train_xgboost()
