import pandas as pd
import numpy as np
from catboost import CatBoostRegressor, Pool
from sklearn.metrics import mean_squared_error
import os
from pipeline_utils import CAT_COLS, require_nvidia_gpu
from validation import get_validation_splits, validate_fold_partition

def train_catboost(data_dir='data'):
    require_nvidia_gpu()
    print("Loading data for CatBoost training...")
    train = pd.read_csv(os.path.join(data_dir, 'inputs', 'Train.csv'))
    features = pd.read_parquet(os.path.join(data_dir, 'processed', 'all_features.parquet'))

    print("Merging train labels with engineered features...")
    df = train.merge(features, on='UniqueID', how='left')

    # Convert object columns to strings for CatBoost
    for c in CAT_COLS:
        if c in df.columns:
            df[c] = df[c].fillna('Unknown').astype(str)

    drop_cols = ['UniqueID', 'BirthDate', 'next_3m_txn_count']
    feature_cols = [c for c in df.columns if c not in drop_cols]
    
    # Fill remaining nulls with 0
    df[feature_cols] = df[feature_cols].fillna(0)

    X = df[feature_cols]
    y = np.log1p(df['next_3m_txn_count'])

    print(f"Training CatBoost model on {len(X)} rows and {len(feature_cols)} features...")

    folds = get_validation_splits(df, y, n_splits=5, random_state=42)
    validate_fold_partition(folds, len(df))
    models = []
    oof_preds = np.zeros(len(X))
    
    cat_features = [c for c in CAT_COLS if c in X.columns]

    for fold, (train_idx, val_idx) in enumerate(folds):
        X_train, y_train = X.iloc[train_idx], y.iloc[train_idx]
        X_val, y_val = X.iloc[val_idx], y.iloc[val_idx]

        train_pool = Pool(X_train, y_train, cat_features=cat_features)
        val_pool = Pool(X_val, y_val, cat_features=cat_features)

        params = {
            'iterations': 5000,
            'learning_rate': 0.02,
            'depth': 8,
            'l2_leaf_reg': 3,
            'loss_function': 'RMSE',
            'eval_metric': 'RMSE',
            'random_seed': 42 + fold,
            'task_type': 'GPU',
            'verbose': 500,
            'early_stopping_rounds': 100
        }

        ### AUTOGENERATED PIPELINE ###
        params["learning_rate"] = 0.03
        params["depth"] = 6
        params["l2_leaf_reg"] = 3.0
        params["random_strength"] = 1.0
        ### END AUTOGENERATED PIPELINE ###

        model = CatBoostRegressor(**params)

        model.fit(train_pool, eval_set=val_pool)

        models.append(model)
        oof_preds[val_idx] = model.predict(X_val)
        
        fold_rmse = np.sqrt(mean_squared_error(y_val, oof_preds[val_idx]))
        print(f"Fold {fold+1} Validation RMSLE: {fold_rmse:.4f}")

    overall_rmse = np.sqrt(mean_squared_error(y, oof_preds))
    print(f"Overall CatBoost OOF RMSLE: {overall_rmse:.4f}")

    # Save OOF predictions
    oof_df = pd.DataFrame({
        'UniqueID': df['UniqueID'],
        'pred_catboost': oof_preds
    })
    oof_df.to_csv(os.path.join(data_dir, 'processed', 'oof_catboost.csv'), index=False)
    print("OOF predictions saved to data/processed/oof_catboost.csv")

    os.makedirs('models', exist_ok=True)
    for i, m in enumerate(models):
        m.save_model(f'models/catboost_fold{i}.cbm')
    
    print("CatBoost Models successfully saved to 'models/' directory.")
    return models

if __name__ == "__main__":
    train_catboost()
